### ISSUE TITLE
disallow post screen when not available

### ISSUE THREAD

**Issue by TPGamesNL** [DBL-App-development-2023-G7/musicmap#101]
Currently, when the post screen isn't available (either because account isn't connected to Spotify, or because Google Play Services is not available), we display a failure message, but still show the screen after this. We should either not show the screen at all (e.g. navigate back to feed when attempting to open it), or make it very clear that it cannot be used (e.g. disable all interaction & grey everything out)

**Comment by viliamDokov** [comment]
Created a new branch with a potential fix. Sadly I did not use `LiveData` so the code right now is a bit cringe. The most awful part is the `waitUserFuture()`. If I could wrap some of the data in the session class as `LiveData` then the code would be much cleaner but I believe this is out of the timescope of this assignment as this would cascade into more refactoring changes. If anyone has a better shorter term solution I would be glad to know.
