### ISSUE TITLE
make README

### ISSUE THREAD

**Issue by TPGamesNL** [DBL-App-development-2023-G7/musicmap#106]
see assignment description: https://canvas.tue.nl/courses/21827/assignments/94661

**Comment by DonaldDuckEde** [comment]
Hi, i would love to help but i can't because i need a login to see that page.

**Comment by TPGamesNL** [comment]
@DonaldDuckEde thanks for your interest in our project. However, this is a university project we're doing, and it's not open for anyone to collaborate, unfortunately. The only reason it's public is to make use of some advantages of GitHub, that it only provides for public repositories.

Out of curiosity, how did you find this project?

**Comment by DonaldDuckEde** [comment]
I was looking for a project to collab on and saw this one, and i want to go to the TUE in about 2 years.

**Comment by TPGamesNL** [comment]
Oh cool haha. I don't think many projects from courses on TUe you'll find on here allow collaboration, I don't think the teachers like it when an outside collaborator helps a group.

I would recommend studying at TUe though, it's a very nice university :)
